<a href="https://colab.research.google.com/github/Kashifletslearn/Day-16-30/blob/main/Day_16_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello i am Kashif khan let's learn together

1.   Github   : https://github.com/Kashifletslearn/Day-16-30
2.   Linkedin : https://www.linkedin.com/in/kashifkhank/
3.   Gmail    : kashifdocument11@gmail.com





#For suggestions and improvement Email me


# <u>**Problem 1**</u>

### Construct a 2-D 10*10 matrix with the following constraints:

*  ####  The element at [0,0] should be 1
*  ####   The element at [0,9] should be 100
* ####   The element at [9,0] should be 50
* ####   The interval between elements in rows should be constant
* ####   The interval between elements in columns should be constant



In [3]:
import numpy as np

first_row=np.linspace(1,50,10,endpoint=True)
emmty_list=[]

for i in first_row:
  emmty_list.append(np.linspace(i,i*100,10,endpoint=True,dtype=int))

new_array=np.array(emmty_list)
print(new_array)

[[   1   12   23   34   45   56   67   78   89  100]
 [   6   77  148  219  290  360  431  502  573  644]
 [  11  142  273  404  535  665  796  927 1058 1188]
 [  17  208  398  589  780  970 1161 1352 1542 1733]
 [  22  273  523  774 1025 1275 1526 1776 2027 2277]
 [  28  338  649  959 1270 1580 1890 2201 2511 2822]
 [  33  404  774 1144 1515 1885 2255 2626 2996 3366]
 [  39  469  899 1329 1760 2190 2620 3050 3480 3911]
 [  44  534 1024 1514 2005 2495 2985 3475 3965 4455]
 [  50  600 1150 1700 2250 2800 3350 3900 4450 5000]]
